version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: djangocms-cascade
    versions:
    - 1.3.7
    - "2.0"
    - 2.0.1
    - 2.0.2
    - 2.0.3
    - 2.0.5
  - dependency-name: django-select2
    versions:
    - 7.6.1
    - 7.6.2
    - 7.7.0
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
    - 3.1.7
  - dependency-name: django-auth-ldap
    versions:
    - 2.3.0
  - dependency-name: bleach
    versions:
    - 3.2.3
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
