#!/bin/bash
# wrapper script to check project for potential problems

# activate virtualenv when necessary
if [ -z ${VIRTUAL_ENV+x} ]; then
    source venv/bin/activate
fi

# enable really all warnings, some of them are silenced by default
if [ "$1" = "--all" ]; then
    export PYTHONWARNINGS=all
fi

# run cms check which seems to include standard manage.py check
./manage.py cms check
