#!/bin/bash
# wrapper script to check project for potential problems

# activate virtualenv when necessary
if [ -z ${VIRTUAL_ENV+x} ]; then
    source venv/bin/activate
fi

# enable deprecation warnings which are silenced by default
export PYTHONWARNINGS=all

# run cms check which seems to include standard manage.py check
./manage.py cms check
