# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-17 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d120', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecolorextension',
            name='color',
            field=models.CharField(blank=True, choices=[('#CC4C03', 'Orange'), ('#B90F22', 'Red'), ('#804597', 'Purple'), ('#00689D', 'Blue'), ('#009D81', 'Turquoise'), ('#6A8B22', 'Green')], max_length=16, verbose_name='Color'),
        ),
    ]
