# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d120', '0002_auto_20161217_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecolorextension',
            name='color',
            field=models.CharField(blank=True, choices=[('#CC4C03', 'Orange'), ('#B90F22', 'Red'), ('#804597', 'Purple'), ('#00689D', 'Blue'), ('#009D81', 'Turquoise'), ('#6A8B22', 'Green'), ('#0083CC', 'Light Blue')], max_length=16, verbose_name='Color'),
        ),
    ]
